### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by dunods** [ptejada/artillery-engine-socketio-v3#2]
i want to load test my socket.io ver 3 application, is there any brief way actually to install and use this package .

**Comment by ptejada** [comment]
@dunods 
Is this info in the README file helpful?
https://github.com/ptejada/artillery-engine-socketio-v3#install--configure

**Comment by dunods** [comment]
i did try that but nothing works. where should I install in a fresh folder ?? and how do I run the code ?

**Comment by ptejada** [comment]
@dunods 
Can you be more specific on what does not work? "nothing works" is not very helpful.

Did you follow this steps to install artillery?
https://artillery.io/docs/guides/getting-started/installing-artillery.html

**Comment by dunods** [comment]
finally manage to run it. so i create fresh folder and install the package. and run the package using this $(npm bin)/artillery... thanks @ptejada
